title: DnA Artists
logo: /assets/img/logo.png
description: Artists & Friends
excerpt_separator: <!--more-->
google_analytics:
theme: jekyll-theme-minimal
plugins: 
  - jekyll-feed
  - jekyll-paginate
collections:
  events:
    output: false
    title: true
    date: true
    time: true
    location: true
    address: true
  publications:
    output: true
    title: true
    date: true
    img: true
    desc: true
    
# post_img: /assets/img/post/
