title: DnA Artists
logo: /assets/img/logo.png
description: Artists & Friends
excerpt_separator: <!--more-->
google_analytics:
theme: jekyll-theme-minimal
plugins: 
  - jekyll-feed
  - jekyll-paginate
collections:
  events:
    output: false
    title: true
    event_date: true
    location: true
    address: true
    sort_by: event_date

