title: DnA Artists
logo: /assets/img/logo.png
description: Artists & Friends
excerpt_separator: <!--more-->
google_analytics:
theme: jekyll-theme-minimal
plugins: 
  - jekyll-feed
  - jekyll-paginate
collections:
  - events:
      title: true
      
      output: false
      #permalink: /:collection/:name/
