title: DnA Artists
logo: /assets/img/logo.png
description: Artists & Friends
excerpt_separator: <!--more-->
google_analytics:
theme: jekyll-theme-minimal
paginate: 5
paginate_path: "/blog/page:num/"
plugins: 
  - jekyll-feed
  - jekyll-paginate
  
collections:
  events:
    output: true
    title: true
    date: true
    event_date: true
    time: true
    location: true
    address: true
  danapublications:
    output: true
    title: true
    date: true
    author: true
    img: true
    desc: true
  alexpublications:
    output: true
    title: true
    date: true
    author: true
    img: true
    desc: true
  dnapublications:
    output: true
    title: true
    date: true
    author: true
    img: true
    desc: true
    
# post_img: /assets/img/post/
