title: DnA Artists  
logo: /assets/img/logo3.png
description: Artists & Friends
excerpt_separator: <!--more-->
google_analytics:
theme: jekyll-theme-minimal
plugins: 
  - jekyll-feed
  - jekyll-paginate
gems:
  - jekyll-feed
  - jekyll-paginate
