title: DnA Artists  
logo: /assets/img/logo.png
alt: ["A black lineart drawing of a cute cat face and bunny face next to each other with 'DnA' written below"]
description: Artists & Friends
excerpt_separator: <!--more-->
google_analytics:
theme: jekyll-theme-minimal
plugins: 
  - jekyll-feed
  - jekyll-paginate
gems:
  - jekyll-feed
  - jekyll-paginate
